### ISSUE TITLE
Selecting directory does not work

### ISSUE THREAD

**Issue by vige** [WunderWungiel/WunderFTP#1]
Selecting directory doesn't seem to have any effect. It's always the home directory which is served.

**Comment by WunderWungiel** [comment]
Are you running latest version?

**Comment by vige** [comment]
> Are you running latest version?

I was testing the version in Harbour. Which, looking at the git log, is probably not quite up-to-date. Please upload updated version :)

**Comment by WunderWungiel** [comment]
Uploaded 0.2-1 (latest).
Sorry for causing trouble, it was just I requested QA before the update fixing directory.

**Comment by vige** [comment]
Hi,

Unfortunately the new version failed the rpm validator checks, as you  
seem to have forgotten the sandboxing line  in the .desktop file :/

  -Ville

Lainaus Wunder Wungiel ***@***.***>:

**Comment by WunderWungiel** [comment]
@vige Fixed, uploaded correct version that passes tests. Sorry for all troubles.

**Comment by vige** [comment]
Thank you!
